on:
  push:
    branches: main

name: Render and Publish

jobs:
  render-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      
      # install python so we can have Jupyter
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # install Jupyter
      - name: install Jupyter
        run: pip install jupyter
      
      # From https://github.com/julia-actions/setup-julia
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.9.4
      
      - name: Set up Julia environment
        run: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.build("IJulia")'

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
  